env:
  github_token: "ENCRYPTED[b44e01386b75af204b5f11f4a81455483f4d3622390903a4ab6c2d664f147b730eaa8cd20c1ce42963654b907210cb5d]"
  rclone_config: "ENCRYPTED[d349ee74e132411e64c52da40b5c05ed34aaa78e9ff40848c05b5ba35825bf0109c9e44a0a774e6562ec506635fb575e]"
  telegram_bot_token: "ENCRYPTED[e470c5bfb4222f2ca709bcb1c6d27bebf9dd69b7082f12ac25a6d4ee7a3fef97a389428c97e282e976bd9e129878908f]"
  telegram_id_channel: "ENCRYPTED[767234cebc0d269d772ad092d2d4870e9251c03ce3308c8f6e06177fdd2ad3fec23fe98ab0da1412913fe0e605e5064a]"

task:
  name: "test script"
  timeout_in: 120m
  container:
    image: inok2341/anu:latest
    cpu: 8
    memory: 32G

  Build-Env-Setup_background_script:
    - export DEBIAN_FRONTEND=noninteractive
    - mkdir -p ~/.config/rclone
    - echo "$rclone_config" > ~/.rclone.conf
    - git config --global user.name "Raya Mahardika"
    - git config --global user.email "rayapkun@gmail.com"
    - echo "$github_token" > ~/.git-credentials
    - git config --global credential.helper store --file=~/.git-credentials
    - rm -rf ~/ccache
    - mkdir -p ~/ccache
    - rclone copy chel:DerpCcache/ccache.tar.gz ~/ -P
    - cd ~/
    - time tar xf ccache.tar.gz
    - cd ~/

  Storage-Checker_background_script:
    - df -h
    - lsblk
    - ls -l -a -h
    - ./sleep.sh

  Sync_script:
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Starting sync DerpFest Android 13 source...."
    - rm -rf ~/rom
    - mkdir -p ~/rom
    - cd ~/rom
    - rm -rf * .repo
    - repo init -q --no-repo-verify --depth=1 -u https://github.com/DerpFest-AOSP/manifest.git -b 13 -g default,-mips,-darwin,-notdefault
    - git clone https://github.com/licacicu/local_manifest --depth=1 .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Sync DerpFest Android 13 source completed!"

  Build_script:
    - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build DerpFest Android 13 started...."
    - ./final.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build $(cd ~/rom/out/target/product/tissot/ && ls DerpFest*.zip) completed!"
    #- ./collect.sh
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Compressing ccache...."

  Upload_script:
    #- ./compressing.sh
    - cd ~/
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading ccache...."
    #- rclone copy ccache.tar.gz chel:DerpCcache -P
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Ccache DerpFest Android 13 uploaded successfully!"
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Uploading build...."
    - rclone copy ~/rom/out/target/product/tissot/DerpFest*.zip chel:ROM -P
    - curl -s https://api.telegram.org/$telegram_bot_token/sendMessage -d chat_id=$telegram_id_channel -d text="Build $(cd ~/rom/out/target/product/tissot/ && ls DerpFest*.zip) uploaded successfully!"
 
